config/routes.rb
Rails.application.routes.draw do
  get 'administrador_dashboard', to: 'dashboards#administrador'
  get 'atendente_dashboard', to: 'dashboards#atendente'
  get 'funcionario_dashboard', to: 'dashboards#funcionario'
  get 'visitante_dashboard', to: 'dashboards#visitante'
  get '/funcionarios', to: 'funcionarios#index'

  resources :setores do
    member do
      get 'funcionarios'
    end
  end
  get '/setores_por_unidade/:unidade_id', to: 'setores#por_unidade'

  resources :unidades
  resources :setores
  resources :funcionarios
  resources :usuarios
  # Outras rotas do Devise
  devise_for :users

  # Rotas para visitas
  resources :visitas do
    collection do
      get :load_funcionarios
      get 'anteriores'  # Rota para visitas anteriores
    end
    member do
      patch :confirmar  # Rota para confirmar visita
    end
  end

  # Rotas para o dashboard
  get 'dashboard/administrador', to: 'dashboards#administrador'
  get 'dashboard/atendente', to: 'dashboards#atendente'
  get 'dashboard/funcionario',   to: 'dashboards#funcionario'
  get 'dashboard/visitante',     to: 'dashboards#visitante'

  get 'visitantes/buscar', to: 'visitantes#buscar'


  # Defines the root path route ("/")
  # root "posts#index"
  # Define a tela de login como root corretamente com devise_scope
  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/models/unidade.rb
class Unidade < ApplicationRecord
  self.table_name = 'unidades'  # Nome da tabela deve ser "unidades"
  
  # Associações
  has_and_belongs_to_many :setors, join_table: 'setors_unidades' # Relação entre unidades e setores
  has_many :users # Uma unidade pode ter vários atendentes
  has_many :setors
  
  validates :nome, presence: true, uniqueness: true
  validates :descricao, presence: true
end

app/controllers/unidades_controller.rb
class UnidadesController < ApplicationController
  before_action :set_unidade, only: %i[edit update destroy]

  def index
    @unidades = Unidade.page(params[:page]).per(10)

  end

  def new
    @unidade = Unidade.new
  end

  def create
    @unidade = Unidade.new(unidade_params)
    if @unidade.save
      redirect_to unidades_path, notice: 'Unidade criada com sucesso!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @unidade.update(unidade_params)
      redirect_to unidades_path, notice: 'Unidade atualizada com sucesso!'
    else
      render :edit
    end
  end

  def destroy
    @unidade.destroy
    redirect_to unidades_path, notice: 'Unidade excluída com sucesso!'
  end

  private

  def set_unidade
    @unidade = Unidade.find(params[:id])
  end

  def unidade_params
    params.require(:unidade).permit(:nome, :descricao)
  end
end

app/helpers/unidades_helper.rb
module UnidadesHelper
end

app/views/unidades/edit.html.erb
<h1>Editar Unidade</h1>

<%= form_with(model: @unidade, local: true) do |form| %>
  <div class="mb-3">
    <%= form.label :nome, "Nome" %>
    <%= form.text_field :nome, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :descricao, "Descrição" %>
    <%= form.text_area :descricao, class: "form-control" %>
  </div>

  <%= form.submit "Atualizar", class: "btn btn-success" %>
  <%= link_to 'Cancelar', unidades_path, class: 'btn btn-secondary' %>
<% end %>

app/views/unidades/index.html.erb
<div class="header-container">
  <h1>Unidades</h1>
  <%= link_to 'Adicionar +', new_unidade_path, class: 'btn btn-primary' %>
</div>

<p>Para criar uma nova unidade, clique no botão “Adicionar +”.</p>

<table class="table table-striped mt-3">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Setores</th>
      <th>Atendentes</th>
      <th>Funcionários</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @unidades.each do |unidade| %>
      <tr>
        <td><%= unidade.nome %></td>
        <td><%= unidade.descricao %></td>
        <td>
          <% setores = Setor.where(unidade_id: unidade.id) %>
          <% if setores.any? %>
            <ul>
              <% setores.each do |setor| %>
                <li><%= setor.nome %></li>
              <% end %>
            </ul>
          <% else %>
            <p>Sem setores</p>
          <% end %>
        </td>
        <td>
          <% atendentes = User.where(role: 'atendente', unidade_id: unidade.id) %>
          <% if atendentes.any? %>
            <ul>
              <% atendentes.each do |atendente| %>
                <li><%= atendente.nome %></li>
              <% end %>
            </ul>
          <% else %>
            <p>Sem atendentes</p>
          <% end %>
        </td>
        <td>
          <% funcionarios = User.where(role: 'funcionario', unidade_id: unidade.id) %>
          <% if funcionarios.any? %>
            <ul>
              <% funcionarios.each do |funcionario| %>
                <li><%= funcionario.nome %></li>
              <% end %>
            </ul>
          <% else %>
            <p>Sem funcionários</p>
          <% end %>
        </td>
        <td>
        <%= link_to edit_unidade_path(unidade), class: 'btn btn-warning btn-sm' do %>
          <i class="fas fa-edit"></i>
        <% end %>
      
        <%= link_to unidade_path(unidade), method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-danger btn-sm' do %>
          <i class="fas fa-trash"></i>
        <% end %>
      </td>
      
      </tr>
    <% end %>
  </tbody>
</table>

<!-- PAGINAÇÃO -->
<div class="pagination">
  <%= paginate @unidades %>
</div>

app/views/unidades/new.html.erb
<h1>Nova Unidade</h1>

<%= form_with(model: @unidade, local: true) do |form| %>
  <div>
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :descricao %>
    <%= form.text_area :descricao %>
  </div>

  <div>
    <%= form.submit 'Criar Unidade', class: 'btn btn-success' %>
  </div>
<% end %>

<%= link_to 'Voltar', unidades_path, class: 'btn btn-secondary' %>