config/routes.rb
Rails.application.routes.draw do
  get 'administrador_dashboard', to: 'dashboards#administrador'
  get 'atendente_dashboard', to: 'dashboards#atendente'
  get 'funcionario_dashboard', to: 'dashboards#funcionario'
  get 'visitante_dashboard', to: 'dashboards#visitante'
  get '/funcionarios', to: 'funcionarios#index'

  resources :setores do
    member do
      get 'funcionarios'
    end
  end
  get '/setores_por_unidade/:unidade_id', to: 'setores#por_unidade'

  resources :unidades
  resources :setores
  resources :funcionarios
  resources :usuarios
  # Outras rotas do Devise
  devise_for :users

  # Rotas para visitas
  resources :visitas do
    collection do
      get :load_funcionarios
      get 'anteriores'  # Rota para visitas anteriores
    end
    member do
      patch :confirmar  # Rota para confirmar visita
    end
  end

  # Rotas para o dashboard
  get 'dashboard/administrador', to: 'dashboards#administrador'
  get 'dashboard/atendente', to: 'dashboards#atendente'
  get 'dashboard/funcionario',   to: 'dashboards#funcionario'
  get 'dashboard/visitante',     to: 'dashboards#visitante'

  get 'visitantes/buscar', to: 'visitantes#buscar'


  # Defines the root path route ("/")
  # root "posts#index"
  # Define a tela de login como root corretamente com devise_scope
  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/controllers/setores_controller.rb
class SetoresController < ApplicationController
  before_action :set_setor, only: %i[show edit update destroy]

  def index
    @setores = Setor.all
  end

  def show
  end

  def new
    @setor = Setor.new
  end

  def create
    @setor = Setor.new(setor_params)
    if @setor.save
      redirect_to setores_path, notice: 'Setor criado com sucesso!'
    else
      puts @setor.errors.full_messages # Adicionando um debug
      render :new
    end
  end
  
  

  def edit
  end

  def update
    if @setor.update(setor_params)
      redirect_to setore_path(@setor), notice: 'Setor atualizado com sucesso!'
    else
      render :edit
    end
  end

  def por_unidade
    setores = Setor.where(unidade_id: params[:unidade_id])
    render json: setores
  end
  
  def destroy
    @setor.destroy
    redirect_to setores_path, notice: 'Setor excluído com sucesso!'
  end

  def show
    @setor = Setor.find(params[:id])
  end
  def funcionarios
    @setor = Setor.find(params[:id])
    @funcionarios = @setor.funcionarios
    respond_to do |format|
      format.json { render json: @funcionarios.select(:id, :nome) }
    end
  end
  private

  def set_setor
    @setor = Setor.find(params[:id])
  end

  def setor_params
    params.require(:setor).permit(:nome, :descricao, :unidade_id)
  end
  
end

app/helpers/setores_helper.rb
module SetoresHelper
end

app/views/setores/edit.html.erb
<h1>Editar Setor</h1>

<%= form_with(model: @setor, url: setore_path(@setor), method: :patch, local: true) do |form| %>
  <div class="mb-3">
    <%= form.label :nome, "Nome" %>
    <%= form.text_field :nome, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :descricao, "Descrição" %>
    <%= form.text_area :descricao, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :unidade_id, "Unidade" %>
    <%= form.collection_select :unidade_id, Unidade.all, :id, :nome, prompt: "Selecione uma unidade", class: "form-control" %>
  </div>

  <%= form.submit "Atualizar", class: "btn btn-success" %>
  <%= link_to 'Cancelar', setores_path, class: 'btn btn-secondary' %>
<% end %>

app/views/setores/index.html.erb
<div class="header-container">
  <h1>Setores</h1>
<%= link_to 'Adicionar +', new_setore_path, class: 'btn btn-primary' %>
</div>

<p>Para criar um novo setor, clique no botão “Adicionar +”.</p>


<table class="table table-striped mt-3">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Unidade</th>
      <th>Funcionários</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @setores.each do |setor| %>
      <tr>
        <td><%= setor.nome %></td>
        <td><%= setor.descricao %></td>
        <td><%= setor.unidade&.nome || 'Sem unidade' %></td>
        <td>
          <% funcionarios = User.where(role: 'funcionario', setor_id: setor.id) %>
          <% if funcionarios.any? %>
            <ul>
              <% funcionarios.each do |funcionario| %>
                <li><%= funcionario.nome %></li>
              <% end %>
            </ul>
          <% else %>
            <p>Sem funcionários</p>
          <% end %>
        </td>
        <td>
        <%= link_to edit_setore_path(setor), class: 'btn btn-warning btn-sm' do %>
          <i class="fas fa-edit"></i>
        <% end %>
        
        <%= link_to setore_path(setor), method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-danger btn-sm' do %>
          <i class="fas fa-trash"></i>
        <% end %>
      </td>
      
      </tr>
    <% end %>
  </tbody>
</table>

app/views/setores/new.html.erb
<h1>Novo Setor</h1>

<%= form_with(model: @setor, url: setores_path) do |form| %>
  <div>
    <%= form.label :nome %>
    <%= form.text_field :nome, required: true %>
  </div>

  <div>
    <%= form.label :descricao %>
    <%= form.text_area :descricao, required: true %>
  </div>

  <div>
    <%= form.label :unidade_id, "Unidade" %>
    <%= form.collection_select :unidade_id, Unidade.all, :id, :nome, prompt: "Selecione uma unidade", required: true %>
  </div>

  <div>
    <%= form.submit "Criar Setor", class: "btn btn-success" %>
  </div>
<% end %>

<%= link_to 'Voltar', setores_path, class: 'btn btn-secondary' %>

app/views/setores/show.html.erb
<h1><%= @setor.nome %></h1>
<p><%= @setor.descricao %></p>

<h2>Funcionários</h2>
<ul>
  <% @setor.funcionarios.each do |funcionario| %>
    <li><%= funcionario.nome %></li>
  <% end %>
</ul>

<%= link_to "Editar", edit_setore_path(@setor) %> |
<%= link_to 'Voltar', setores_path %>