config/routes.rb
Rails.application.routes.draw do
  get 'administrador_dashboard', to: 'dashboards#administrador'
  get 'atendente_dashboard', to: 'dashboards#atendente'
  get 'funcionario_dashboard', to: 'dashboards#funcionario'
  get 'visitante_dashboard', to: 'dashboards#visitante'
  get '/funcionarios', to: 'funcionarios#index'

  resources :setores do
    member do
      get 'funcionarios'
    end
  end
  get '/setores_por_unidade/:unidade_id', to: 'setores#por_unidade'

  resources :unidades
  resources :setores
  resources :funcionarios
  resources :usuarios
  # Outras rotas do Devise
  devise_for :users

  # Rotas para visitas
  resources :visitas do
    collection do
      get :load_funcionarios
      get 'anteriores'  # Rota para visitas anteriores
    end
    member do
      patch :confirmar  # Rota para confirmar visita
    end
  end

  # Rotas para o dashboard
  get 'dashboard/administrador', to: 'dashboards#administrador'
  get 'dashboard/atendente', to: 'dashboards#atendente'
  get 'dashboard/funcionario',   to: 'dashboards#funcionario'
  get 'dashboard/visitante',     to: 'dashboards#visitante'

  get 'visitantes/buscar', to: 'visitantes#buscar'


  # Defines the root path route ("/")
  # root "posts#index"
  # Define a tela de login como root corretamente com devise_scope
  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
    before_action :authenticate_user! # Garante que o usuário esteja logado
    before_action :set_usuario, only: [:edit, :update]

    def index
      @usuarios = User.where.not(role: 'visitante').page(params[:page]).per(10)
    end

    def new
      @usuario = User.new
    end
  
    def create
      @usuario = User.new(usuario_params)
      
      if @usuario.save
        redirect_to root_path, notice: "Usuário criado com sucesso!"
      else
        render :new
      end
    end

    def edit
      # Aqui estamos carregando o usuário para editar, a partir do ID
    end
  
    def update
      if @usuario.update(usuario_params)
        redirect_to usuarios_path, notice: "Usuário atualizado com sucesso!"
      else
        render :edit
      end
    end

    private
  def set_usuario
    @usuario = User.find(params[:id])  # Certifique-se de que o ID está sendo passado corretamente
  rescue ActiveRecord::RecordNotFound
    redirect_to usuarios_path, alert: "Usuário não encontrado"
  end  
    def usuario_params
      params.require(:user).permit(:nome, :email, :password, :password_confirmation, :role, :cpf, :telefone)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/edit.html.erb
<h1>Editar Usuário</h1>

<%= form_for(@usuario, url: usuarios_path(@usuario), method: :patch) do |f| %>
  <div>
    <%= f.label :nome %>
    <%= f.text_field :nome, value: @usuario.nome %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email, value: @usuario.email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div>
    <%= f.label :cpf %>
    <%= f.text_field :cpf, value: @usuario.cpf %>
  </div>

  <div>
    <%= f.label :telefone %>
    <%= f.text_field :telefone, value: @usuario.telefone %>
  </div>

  <div>
    <%= f.label :role, "Função" %>
    <%= f.select :role, User.roles.keys.reject { |role| role == 'visitante' }.map { |role| [role.humanize, role] }, selected: @usuario.role %>
  </div>

  <%= f.submit "Atualizar Usuário" %>
<% end %>

app/views/usuarios/index.html.erb
<div class="header-container">
  <h1>Usuários</h1>
  <%= link_to 'Adicionar +', new_usuario_path, class: 'btn btn-primary' %>
</div>

<p>Para criar um novo usuário, clique no botão “Adicionar +”.</p>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>CPF</th>
      <th>Telefone</th>
      <th>Função</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.cpf %></td>
        <td><%= usuario.telefone %></td>
        <td><%= usuario.role %></td>
        <td>
        <%= link_to edit_usuario_path(usuario), class: 'btn btn-warning' do %>
          <i class="fas fa-edit"></i> <!-- Ícone de edição -->
        <% end %>
      
        <%= link_to usuario_path(usuario), method: :delete, data: { confirm: 'Tem certeza que deseja excluir este usuário?' }, class: 'btn btn-danger' do %>
          <i class="fas fa-trash"></i> <!-- Ícone de lixeira -->
        <% end %>
      </td>
      
      </tr>
    <% end %>
  </tbody>
</table>

<!-- Adiciona a paginação -->
<div class="pagination">
  <%= paginate @usuarios %>
</div>

app/views/usuarios/new.html.erb
<h1>Novo Usuário</h1>

<p>Preencha os campos abaixo para criar um novo usuário.</p>

<%= form_for(@usuario, url: usuarios_path, method: :post) do |f| %>
  <div class="form-group">
    <%= f.label :nome, class: "form-label" %>
    <%= f.text_field :nome, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email, class: "form-label" %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password, class: "form-label" %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, class: "form-label" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :cpf, class: "form-label" %>
    <%= f.text_field :cpf, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :telefone, class: "form-label" %>
    <%= f.text_field :telefone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :role, "Função", class: "form-label" %>
    <%= f.select :role, User.roles.keys.reject { |role| role == 'visitante' }.map { |role| [role.humanize, role] }, {}, class: "form-control" %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Prosseguir", class: "btn btn-primary" %>
  </div>
<% end %>