config/routes.rb
Rails.application.routes.draw do
  get 'administrador_dashboard', to: 'dashboards#administrador'
  get 'atendente_dashboard', to: 'dashboards#atendente'
  get 'funcionario_dashboard', to: 'dashboards#funcionario'
  get 'visitante_dashboard', to: 'dashboards#visitante'
  get '/funcionarios', to: 'funcionarios#index'

  resources :setores do
    member do
      get 'funcionarios'
    end
  end
  get '/setores_por_unidade/:unidade_id', to: 'setores#por_unidade'

  resources :unidades
  resources :setores
  resources :funcionarios
  resources :usuarios
  # Outras rotas do Devise
  devise_for :users

  # Rotas para visitas
  resources :visitas do
    collection do
      get :load_funcionarios
      get 'anteriores'  # Rota para visitas anteriores
    end
    member do
      patch :confirmar  # Rota para confirmar visita
    end
  end

  # Rotas para o dashboard
  get 'dashboard/administrador', to: 'dashboards#administrador'
  get 'dashboard/atendente', to: 'dashboards#atendente'
  get 'dashboard/funcionario',   to: 'dashboards#funcionario'
  get 'dashboard/visitante',     to: 'dashboards#visitante'

  get 'visitantes/buscar', to: 'visitantes#buscar'


  # Defines the root path route ("/")
  # root "posts#index"
  # Define a tela de login como root corretamente com devise_scope
  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Visit Track" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
<link rel="manifest" href="/manifest.json">
<!-- Substitua pelos caminhos corretos para os arquivos de imagem na pasta assets -->
<link rel="icon" href="<%= asset_path('logo.png') %>" type="image/png">
<link rel="apple-touch-icon" href="<%= asset_path('logo.png') %>">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <%= javascript_importmap_tags %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">

    </head>

  <body>
  <% if user_signed_in? %>
  <header class="fixed-header">
    <nav class="nav-container">
      <div class="logo">
        <%= link_to root_path do %>
          <%= image_tag "logo.png", alt: "VisitTrack Logo", class: "logo-img" %>
        <% end %>
      </div>
      <div class="logout-btn">
      <%= link_to destroy_user_session_path, 
          data: { turbo_method: :delete, confirm: "Tem certeza que deseja sair?" }, 
          class: "btn btn-danger logout-btn" do %>
        <i class="fas fa-sign-out-alt"></i> <!-- Ícone de logout -->
        Sair
      <% end %>
    </div>
        </nav>
  </header>
  <% if current_user&.role == "administrador" %>
  <!-- Menu lateral -->
  <div class="menu-container">
    <%= link_to unidades_path, style: "text-decoration: none; color: inherit;" do %>
      <div class="menu-item">
        <i class="fas fa-building"></i>
        <h3>Unidades</h3>
      </div>
    <% end %>

    <%= link_to setores_path, style: "text-decoration: none; color: inherit;" do %>
      <div class="menu-item">
        <i class="fas fa-layer-group"></i>
        <h3>Setores</h3>
      </div>
    <% end %>

    <%= link_to funcionarios_path, style: "text-decoration: none; color: inherit;" do %>
      <div class="menu-item">
        <i class="fas fa-users"></i>
        <h3>Funcionários</h3>
      </div>
    <% end %>

    <%= link_to usuarios_path, style: "text-decoration: none; color: inherit;" do %>
      <div class="menu-item">
        <i class="fas fa-user"></i>
        <h3>Usuários</h3>
      </div>
    <% end %>
  </div>
<% end %>
<% end %>


  <main>



    <%= yield %>
  </main>
</body>
</html>